### ISSUE TITLE
Cookie notices are only required when the cookie is "technically unnecessary"

### ISSUE THREAD

**Issue by Ember-ruby** [florisboard/addons-frontend#13]
As the addon store only stores cookie for technically necessary reasons (ie, not tracking), there is no need for a cookie banner.

Having a cookie banner when unnecessary will give users the impression that the website does track them

Source: https://en.m.wikipedia.org/wiki/HTTP_cookie#EU_cookie_directive

**Comment by patrickgold** [comment]
Ok granted you are right, however one could argue though that explaining each cookie adds to the transparency to the site...

**Comment by Ember-ruby** [comment]
probably better in an about/privacy policy page

cookie notices are almost always used by websites tracking you, i would bet a fair few people won't even read it, and assume it's presence means there are tracking cookies

**Comment by 4H1R** [comment]
We understand your point but what we're trying to do is to explain each cookies to users + show them we're not tracking anything
