### ISSUE TITLE
Error when creating new release: version number validation

### ISSUE THREAD

**Issue by itsmartashub** [florisboard/addons-frontend#14]
When attempting to create a new themes release (version `4.0.0`), an error occurs after submitting the form in `Create Release` dialog. The error message states: `The new release should be bigger than previous version which is 3.0.2`

### Screenshot: `Create Release` form
![image](https://github.com/user-attachments/assets/91d030ff-c46a-4ec0-a0d0-6fd72de9d310)

### Screenshot: Floristyle version in metadata (in the `flex` file)
![IMG_20241011_162143](https://github.com/user-attachments/assets/c9697ed2-ff0d-4fa8-8140-c69ad481ceae)

**Comment by patrickgold** [comment]
I've forwarded this issue to Ali as he knows best why this probably goes wrong

**Comment by 4H1R** [comment]
Hi it should be fixed could you try again and let us know

Thank you for your collaboration

**Comment by itsmartashub** [comment]
Yes, it seems like you've fixed it! Submitted successfully. Thank you both for your time 🙏

Of the topic question:

It feels like I’ve submitted updates for the main project image multiple times few days ago, but they haven't been accepted (maybe you thought that it's some mistake because they looks similar). The "new" image is pretty similar to the current one, just with a few minor tweaks like adjusting the aspect ratio and straightening the edges. 
I've noticed over time that you’ve decreised the border-radius across the project overall. Maybe because my image originaly had a larger radius, which made it stick out compared to the other project cards and looks odd overall.

@4H1R Maybe in the future, it would be helpful to set some guidelines or **image rules** for creators. Things like straight edges, no borders or shadows, and recommended aspect ratios or dimensions. That could help keep everything looking more consistent and in line with the design you envisioned

**Comment by 4H1R** [comment]
@itsmartashub Thank you for the suggession We'll write some guidelines for images

Thank you again

Best Regards
